### ISSUE TITLE
DWGReverbC1C3 crashes server

### ISSUE THREAD

**Issue by nhthn** [sonoro1234/DWGReverb#2]
The following crashes the server with `RESULT = 0` on Linux:

```
(
{
    var snd = SinOsc.ar(440);
    snd = snd * Decay2.ar(Impulse.ar(2), 0.01, 0.02);
    snd = DWGReverbC1C3.ar(snd, 2000, 1, 10);
    snd * 0.2;
}.play;
)
```

Going to investigate. EarlyRef ugens are working fine afaict.

**Comment by nhthn** [comment]
The problem is [`DWGReverbC1C3T::get_args`](https://github.com/sonoro1234/DWGReverb/blob/59ea980dba5e39c6e935f1bc41cc2a66d11a4130/Reverb.cpp#L136), lines 147-148.

The SC class is not supplying the eight inputs for o_perm, so it's accessing garbage memory. So it's a matter of the class being out of sync with the inputs demanded by the ugen.

Removing the for loop gets the ugen working, because o_perm is already initialized in [`FDN_HH_Base`](https://github.com/sonoro1234/DWGReverb/blob/a381de620f307b91ad605428e909fb43f37a44f1/dwglib/DWG.hpp#L1017). Or the class can be amended to supply the o_perm inputs. Can you explain what o_perm does, and what values it can take on?

**Comment by sonoro1234** [comment]
@snappizz  thanks for taking care

this is my fault for not using sclang but only Lua2SC.
o_perm is a permutation for indices in fdn matrix
[1,2,3,4,5,6,7,0] should be the default permutation.
when I have some time I should correct sc classes and expose new plugins as DWGReverbC1C3_16 (16x16 fdn matrix),DWGReverb3Band (3 band Eq as Zita rev), DWGReverb3Band_16 and PartitionedConvolutionT (for using EarlyRefGen)

**Comment by sonoro1234** [comment]
@snappizz 
Just updated sclang classes and help
hope everything works!!
