### ISSUE TITLE
how to install!

### ISSUE THREAD

**Issue by cdbzb** [sonoro1234/DWGReverb#3]
This looks fab... is it available as a quark? is it straightforward to install on mac, sorry for foolish question!

**Comment by sonoro1234** [comment]
It is not available as a quark. I only work with my client Lua2SC. I am not sure if "make install" is working (did you tried?) dylib should go in plugins directory and sclang content in SCClassLibrary (at least in windows)

I just tried setting in CMake command CMAKE_INSTALL_PREFIX and all is installed in it, you should set it to the appropiate folder in Mac.

see: https://github.com/sonoro1234/DWGReverb/blob/master/build/init_cmake.bat

1 -change it to mac script (.sh?)
2 -set CMAKE_INSTALL_PREFIX to appropiate folder
You can find this folder for sclang with Platform.userExtensionDir or Platform.systemExtensionDir
also set SC_PATH to supercollider repo folder
3- run it
4- make install

And if it works add this script in build folder and do a PR please.

**Comment by sonoro1234** [comment]
As said in readme see MyUgens
