### ISSUE TITLE
Multichannel Buffers in PartConvT

### ISSUE THREAD

**Issue by mousaique** [sonoro1234/DWGReverb#4]
Hello, 

i was wondering whether PartConvT accepts multichannel buffers for IR buffers? 
Im trying to crossfade between PartConvTs with different IRs but there seems to be no variation?
Heres the example im using in SC:

d=Buffer.alloc(s,2*s.sampleRate,8,0)
(
SynthDef(\mbuf, { |out,amp,dur,seq=#[1,1,1,1,1,1,1,1]|
	
	var rec=RecordBuf.ar(Saw.ar(100*(1..8)),d.bufnum((0..7)));	
	var snd=DXMix.ar(Dseq(seq,inf),`(PartConvT.ar(0.01*Saw.ar(20),2**12,d.bufnum((0..7)),Impulse.kr(1/2))),
		fadeTime: 1,
		fadeMode: 0,
		width: 2,
		maxWidth: 7,
		equalPower: 0, // better here with sines, see curvature options in DXEnvFan help, Ex.1
		initOutOffset: 0);
	
	Out.ar(out,
		Pan2.ar(EnvGen.ar(Env.sine,1,1,timeScale:dur,doneAction:2)*amp*LeakDC.ar(snd)))
}).add;)

(
Pbind(\instrument, \mbuf,
	\seq,Pfunc{[(0..7)]},
	\out,0,
	\dur,20,
	\amp,1/2,
).play)

Thanks for any help,
Jan

**Comment by sonoro1234** [comment]
Buffer number is only readen in the constructor, so it cant be changed

**Comment by mousaique** [comment]
Ok, thank you!
